@startuml

object RegularTermDef {
  Time
  Time
}

object TotalTerm {
  Time
  Time
}

object RestTermDef {
  Time
  Time
}

object WorkingTimes {
}

object WorkingTimesInRegularTermDef {
}

object WorkingTimesOutOfRegularTermDef {
}

WorkingTimes --> WorkingTimesInRegularTermDef
WorkingTimes --> WorkingTimesOutOfRegularTermDef

TotalTerm --> WorkingTimes
TotalTerm --> "*" RestTimes

@enduml