@startuml

class TotalTerms

TotalTerms --> "*" TotalTerm

class WorkingTermInRegularTerms

class WorkingTermOutOfRegularTerms

class WorkingTerms

TotalTerms -[hidden]> WorkingTerms
WorkingTerms -[hidden]-> WorkingTermInRegularTerms
WorkingTermInRegularTerms -[hidden]-> WorkingTermOutOfRegularTerms

@enduml